Ft get guest
offiongbassey/management pull request #11
Opened 2023-08-03 17:44 UTC by offiongbassey

Get Guest feature provides data of guest based on the parameter passed. 

![right](https://github.com/offiongbassey/management/assets/62076877/009da82a-2473-42d5-9d85-79dae4bfa4fa)

2023-08-03 20:08 UTC, eleezs requested changes

2023-08-03 20:08 UTC, eleezs commented on src/controllers/guest.js
> +      return responseHandler(
format in straight line

2023-08-03 20:08 UTC, eleezs commented on src/controllers/guest.js
> +      if (!guests) {
did you test this condition?

2023-08-03 20:08 UTC, eleezs commented on src/middlewares/validator.js
> +        .exists()
why are you using optional and exist on one field?

2023-08-03 20:23 UTC, offiongbassey commented on src/controllers/guest.js
> +      return responseHandler(
Okay. I have done that.

2023-08-03 20:25 UTC, offiongbassey commented on src/middlewares/validator.js
> +        .exists()
I have removed the exists()

2023-08-03 20:26 UTC, offiongbassey commented on src/controllers/guest.js
> +      if (!guests) {
It was returning an empty array but I have fixed it.

2023-08-04 07:18 UTC, eleezs requested changes

2023-08-04 07:18 UTC, eleezs commented on src/controllers/guest.js
> +      if (!guests || guests.length < 1) {
use a chain condition here

2023-08-04 07:18 UTC, eleezs commented on src/middlewares/validator.js
> +    query("gender")
do a check for the datatype as well

2023-08-04 07:18 UTC, eleezs commented on src/controllers/guest.js
> +export const deleteGuest = async (req, res) => {
Why is this controller here?
Is delete not supposed to be in its own branch?

2023-08-04 12:02 UTC, eleezs requested changes

2023-08-04 12:02 UTC, eleezs commented on src/helpers/validation.js
> +export const acceptedStatus = async(status) => {
where is this function been used?

2023-08-04 12:02 UTC, eleezs commented on src/server/migrations/20230802160944-guest.js
is this correct?

2023-08-04 13:57 UTC, eleezs requested changes

2023-08-04 13:57 UTC, eleezs commented on src/middlewares/validator.js
> +        .custom(acceptedStatus)
instead of writing a function for this. Use 
`.isIn['active', 'deleted']
.withMessage("add message")
`
This will check if the status been passed meets what you need

2023-08-04 14:10 UTC, merged