Ft authentication
offiongbassey/management pull request #16
Opened 2023-08-11 11:23 UTC by offiongbassey

Authentication Completed and Guests Minor Errors Fixed along. 
![auth](https://github.com/offiongbassey/management/assets/62076877/1ae188fa-7261-4063-83eb-122b716743fe)

2023-08-15 10:13 UTC, eleezs requested changes

2023-08-15 10:13 UTC, eleezs commented on .gitignore
> +.vscode
Why don't you just delete the file

2023-08-15 10:13 UTC, eleezs commented on src/controllers/auth.js
> +const generateToken = (id) => {
move this to a helper file

2023-08-15 10:13 UTC, eleezs commented on src/controllers/auth.js
> +            role: 'user',
instead of assigning this here, create an endpoint where you can assign someone a role.

2023-08-15 10:13 UTC, eleezs commented on src/controllers/auth.js
> +            role: 'user',
Now, let there be some kind of check, what should the user have or not have for them to be assigned a certain role.

2023-08-15 10:13 UTC, eleezs commented on src/controllers/auth.js
> +export const login = async (req, res) => {
this is not part of the PRD, please read the PRD again

2023-08-15 10:13 UTC, eleezs commented on src/helpers/validation.js
> +export const authExistingEmail = async (email) => {
i thought something that does this check already exist

2023-08-15 10:13 UTC, eleezs commented on src/helpers/validation.js
> +export const authExistingPhone = async (phone) => {
And this one too?

2023-08-15 10:13 UTC, eleezs commented on src/helpers/validation.js
> +export const confirmPassword = async (body) => {
Why is this a custom function, is the validator checks it self not handling this

2023-08-15 10:13 UTC, eleezs commented on src/index.js
> +import cookieParser from "cookie-parser";
Why are we using this again?

2023-08-15 10:13 UTC, eleezs commented on src/server/migrations/20230808215645-create-user.js
> +      role: {
let's assume that the users here are staff.
Staffs in a company have different roles. 
Let the role have a table of its own, and let this user table be linked to the role by the role id(associations).

2023-08-15 10:13 UTC, eleezs commented on yarn-error.log
why is this here again?

2023-08-15 10:13 UTC, eleezs commented on src/server/migrations/20230809220547-user-guests-association-update.js
> +  async up (queryInterface, Sequelize) {
why do we need staff on the guest table?

2023-08-15 16:50 UTC, eleezs requested changes

2023-08-15 16:50 UTC, eleezs commented on src/controllers/auth.js
> +export const assignRole = async (req, res) => {
move to a different controller

2023-08-15 17:36 UTC, offiongbassey commented on .gitignore
> +.vscode
I have done that.

2023-08-15 17:36 UTC, offiongbassey commented on src/controllers/auth.js
> +const generateToken = (id) => {
I have done that.

2023-08-15 17:38 UTC, offiongbassey commented on src/helpers/validation.js
> +export const authExistingEmail = async (email) => {
Noooo. That one was for guest and not user

2023-08-15 17:39 UTC, offiongbassey commented on src/server/migrations/20230808215645-create-user.js
> +      role: {
Okay. I have done that.

2023-08-15 17:40 UTC, offiongbassey commented on yarn-error.log
I have removed it.

2023-08-15 17:41 UTC, offiongbassey commented on src/server/migrations/20230809220547-user-guests-association-update.js
> +  async up (queryInterface, Sequelize) {
the staff_id is simply the user's Id. With the staff_id we will know the staff that created the guest.

2023-08-15 17:47 UTC, offiongbassey commented on src/controllers/auth.js
> +export const assignRole = async (req, res) => {
I have done that.

2023-08-15 17:49 UTC, offiongbassey commented on src/index.js
> +import cookieParser from "cookie-parser";
I'm using that in login. cookieParser's function is to get token from cookies.

2023-08-15 18:08 UTC, offiongbassey commented on src/helpers/validation.js
> +export const confirmPassword = async (body) => {
Okay. I have modified that.

2023-08-17 20:50 UTC, eleezs requested changes

2023-08-17 20:50 UTC, eleezs commented on package.json
> +    "fast-csv": "^4.3.6",
what is this doing here

2023-08-17 20:50 UTC, eleezs commented on package.json
> +    "multer": "^1.4.5-lts.1",
what is this doing here

2023-08-17 20:50 UTC, eleezs commented on src/controllers/auth.js
> +        await  client.setEx(`user_${ user.id.toString() }`, 120, JSON.stringify({ token }));
why are you using a JSON stringfy

2023-08-17 20:50 UTC, eleezs commented on src/controllers/auth.js
> +        const user_data = {id, name, username, phone, gender, status, token};
format properly

2023-08-17 20:50 UTC, eleezs commented on src/controllers/auth.js
> +        const verification = jwt.verify(token, process.env.JWT_SECRET);
create a helper function that does this

2023-08-17 20:50 UTC, eleezs commented on src/controllers/auth.js
> +export const createRole = async (req, res) => {
why is this in auth file?

2023-08-17 20:50 UTC, eleezs commented on src/helpers/validation.js
> +export const authExistingEmail = async (email) => {
abstract this function, they are doing same thing

2023-08-17 20:50 UTC, eleezs commented on src/middlewares/adminAuth.js
> +        const verification = jwt.verify(token, process.env.JWT_SECRET);
This authenticating. user should not be happening In the controller, the middle ware should handle it

2023-08-17 21:18 UTC, offiongbassey commented on src/helpers/validation.js
> +export const authExistingEmail = async (email) => {
existingEmail function is checking from guest table while authExistingEmail is checking from user table. Those are two different tables

2023-08-17 21:21 UTC, offiongbassey commented on package.json
> +    "fast-csv": "^4.3.6",
Okay I will remove that

2023-08-17 21:21 UTC, offiongbassey commented on package.json
> +    "multer": "^1.4.5-lts.1",
I will remove that as well.

2023-08-17 21:25 UTC, offiongbassey commented on src/controllers/auth.js
> +        await  client.setEx(`user_${ user.id.toString() }`, 120, JSON.stringify({ token }));
I have removed it.

2023-08-17 21:38 UTC, offiongbassey commented on src/middlewares/adminAuth.js
> +        const verification = jwt.verify(token, process.env.JWT_SECRET);
This is a middleware File

2023-08-18 07:01 UTC, offiongbassey commented on src/controllers/auth.js
> +        const user_data = {id, name, username, phone, gender, status, token};
I thought as much but there isn't any other way that seems better because I need to eliminate the password and include the token. However, I tried modifying it but adding the token to the object isn't working.

2023-08-18 07:16 UTC, offiongbassey commented on src/controllers/auth.js
> +        const verification = jwt.verify(token, process.env.JWT_SECRET);
Okay. I have done that

2023-08-18 07:23 UTC, offiongbassey commented on src/controllers/auth.js
> +export const createRole = async (req, res) => {
I have removed it.

2023-08-21 07:29 UTC, closed without merging