Ft Authentication
offiongbassey/management pull request #21
Opened 2023-08-21 07:32 UTC by offiongbassey

User 
![authentication](https://github.com/offiongbassey/management/assets/62076877/d9ed7311-3e05-4947-ab37-39d240bcf9fd)
Authentication Completed.

2023-08-22 09:41 UTC, eleezs requested changes

2023-08-22 09:41 UTC, eleezs commented on src/controllers/auth.js
> +        if(username === ""){
make this a function of its own,

2023-08-22 09:41 UTC, eleezs commented on src/helpers/redis_connect.js
move it to the server config folder

2023-08-22 09:56 UTC, offiongbassey commented on src/helpers/redis_connect.js
Okay. I have done that.

2023-08-22 10:17 UTC, offiongbassey commented on src/controllers/auth.js
> +        if(username === ""){
Okay. I have done that.

2023-08-23 14:43 UTC, eleezs approved these changes

2023-08-23 14:43 UTC, merged