Delete Guest Feature Added
offiongbassey/management pull request #8
Opened 2023-08-01 22:22 UTC by offiongbassey

Delete Guest Feature changes status of the guest to deleted and saves the operation in Logs Table. 

![guest deleted](https://github.com/offiongbassey/management/assets/62076877/c01b40e8-a743-4380-bee8-9ebb8f643c6e)

2023-08-02 07:41 UTC, eleezs commented on src/middlewares/validator.js
> +export const delete_guest_validator = [
No check allowed fields?

2023-08-02 07:41 UTC, eleezs commented on src/helpers/validation.js
> +export const confirmGuest = async (id) => {
why did you put this here?

2023-08-02 07:41 UTC, eleezs commented on src/helpers/validation.js
>    // return true;
why is this commented out

2023-08-02 11:10 UTC, offiongbassey commented on src/helpers/validation.js
> +export const confirmGuest = async (id) => {
I have removed it.

2023-08-02 11:22 UTC, eleezs requested changes

2023-08-02 11:22 UTC, eleezs commented on src/server/migrations/20230802162211-create-log.js
> +      description: {
First, this should be an ENUM, containing actions carried out on the system. e.g: created, edited, deleted, 

Next add a payload column: the datatype should be a json,
This should contain the data passed by the user in query, param or body of the request.

2023-08-02 11:22 UTC, eleezs commented on src/server/migrations/20230802162211-create-log.js
> +      userId: {
staff_id is better

2023-08-02 11:22 UTC, eleezs commented on src/server/migrations/20230802160944-guest.js
> +    await queryInterface.addColumn('Guests', 'status', {
status should be an enum: it can contain: active, deleted, blocked, etc

2023-08-02 11:22 UTC, eleezs commented on src/server/models/log.js
> +      // define association here
Add association

2023-08-02 11:58 UTC, offiongbassey commented on src/middlewares/validator.js
> +export const delete_guest_validator = [
I have done it.

2023-08-02 12:16 UTC, offiongbassey commented on src/server/migrations/20230802160944-guest.js
> +    await queryInterface.addColumn('Guests', 'status', {
Okay. I have done that.

2023-08-02 12:57 UTC, offiongbassey commented on src/server/migrations/20230802162211-create-log.js
> +      userId: {
Okay. I have done that.

2023-08-02 12:58 UTC, offiongbassey commented on src/server/migrations/20230802162211-create-log.js
> +      description: {
Okay. I have resolved that.

2023-08-02 12:58 UTC, offiongbassey commented on src/helpers/validation.js
>    // return true;
I've taken it off.

2023-08-02 13:27 UTC, offiongbassey commented on src/server/models/log.js
> +      // define association here
Done

2023-08-03 09:58 UTC, eleezs requested changes

2023-08-03 09:58 UTC, eleezs commented on .gitignore
> +null.js
Please what is this?

2023-08-03 09:58 UTC, eleezs commented on src/controllers/guest.js
> +    return responseHandler(
Please make sure all the responseHandler  is in one line

2023-08-03 09:58 UTC, eleezs commented on src/middlewares/validator.js
> +        .withMessage("Guest Id is a number")
Preferably use "must" instead of "is"

2023-08-03 10:02 UTC, offiongbassey commented on .gitignore
> +null.js
It's actually a file that I wasn't using at the moment. I will remove it

2023-08-03 10:08 UTC, offiongbassey commented on src/middlewares/validator.js
> +        .withMessage("Guest Id is a number")
I have done it.

2023-08-03 10:09 UTC, offiongbassey commented on src/controllers/guest.js
> +    return responseHandler(
I have done that as well.

2023-08-03 10:20 UTC, merged